include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    use_setters_to_change_properties: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    type_annotate_public_apis: false
    avoid_equals_and_hash_code_on_mutable_classes: false