name: loja_hasura
description: A new Flutter project.

publish_to: none
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:  
  oktoast: ^3.2.0
  firebase_auth: ^3.4.2
  find_dropdown: ^1.0.0
  git: ^2.0.0
  hasura_cache_interceptor: 
  hive_cache_interceptor: 
  hasura_connect: 
  dio: ^4.0.6
  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.7+4
  flutter_modular: ^5.0.3
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  effective_dart: ^1.3.2
  mockito: ^5.2.0
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7
  modular_test: ^2.0.0
  flutter_test:
    sdk: flutter

dependency_overrides: 
  hasura_cache_interceptor: 
    git:
      url: https://github.com/Flutterando/hasura_connect.git
      ref: updating-melos
      path: packages/hasura_cache_interceptor

  hive_cache_interceptor: 
    git:
      url: https://github.com/Flutterando/hasura_connect.git
      ref: updating-melos
      path: packages/hive_cache_interceptor

  hasura_connect: 
    git:
      url: https://github.com/Flutterando/hasura_connect.git
      ref: updating-melos
      path: packages/hasura_connect
  #hasura_connect: ^4.0.0+2

scripts:
  watch: flutter pub run build_runner watch
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
